print('Hey,i ate an apple')
print('here is a picture of a bored face')
print('+ +')
print(' - ')
print('i live in victoria')
print('--')
print('| |')
print('| |')
print('--')
print(2025-2009)
print('what is my age? 10')
print('if i were a dog you would be 70')
print('here is a scarf:')
print('~#' * 10)
print('here is a wave')
print('/\ '* 10)
print(' \/'* 10) 
